# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
    desc 'Fetch certificates and provisioning profiles'
    lane :certificates do
        match(app_identifier: 'cc.rent.app', type: 'development', readonly: true)
    end
    
    desc 'Build the iOS application.'
    private_lane :build do
        certificates
        increment_build_number(xcodeproj: './ios/CloverCompany.xcworkspace')
        gym(scheme: 'Release', project: './ios/CloverCompany.xcworkspace')
    end

    lane :beta do
        build
        crashlytics(api_token: "1df0dca4b42c88585130567234678b1d9102cedc",
                    build_secret: "def11e20fb1e9e3a0f6d885998481fa32b35c48237a16cf300c43d792ccb1ec7")
    end
end